Use unordered_map for keydown
cemu-project/Cemu pull request #248
Opened 2022-09-13 12:59 UTC by SSimco

Use an unordered_map Instead of using atomic_bool for keeping the states of the key.
Also, instead of using raw key codes I used virtual key codes from wxWidgets, which are mapped to ImGuiKey. This also makes easier to get the button names on Windows and Linux, where the ImGuiKey values are mapped to their string equivalent.

2022-09-13 20:29 UTC, Exzap requested changes
Thanks for looking into this. I gave this a quick test on Windows and it works, but it also breaks compatibility with existing keyboard profiles which is something that needs to be resolved before we can merge this. There are also some minor changes that should be made to the code, see code comments below.

Another concern I have with this is that hardcoding the key names means we have to manually localize them into each language. API like `GetKeyNameTextA` automatically returns the name in the language matching the keyboard layout. It's not a deal breaker but a solution to get the standardized key names from the OS (in a cross-platform way, if possible) would be preferred.

2022-09-13 20:29 UTC, Exzap commented on src/gui/guiWrapper.h
> +	std::unordered_map<uint32, bool> get_keystates() const
Creating a temporary copy of the entire container is pretty inefficient and in this form it's also not thread-safe.
A better design would be to pass the target map for the copy as a reference, like this:
`void get_keystates(std::unordered_map<uint32, bool>& buttonsOut)`
Then inside the function you can handle the copying/assignment while also locking `keycode_mutex`.

2022-09-13 20:29 UTC, Exzap commented on src/input/emulated/EmulatedController.cpp
> +			auto buttons=controller->get_state().buttons;
```suggestion
			auto& buttons=controller->get_state().buttons;
```
Use a reference here to avoid creating a copy

2022-09-15 19:27 UTC, SSimco commented
Now it doesn't break compatibility with existing keyboard profiles on windows.

I've changed it back to use `GetKeyNameTextA` to get the name in the language matching the keyboard layout on windows.

On linux I've used gdk_keyval_name to get the key name.

2022-09-19 01:04 UTC, Exzap commented
Looks good to me now. I tested this on Windows for a bit and it works as expected with no issues. Thanks!

2022-09-19 01:07 UTC, merged